# Generated by Django 3.2.3 on 2023-07-14 17:57

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, null=True, validators=[api.validators.validate_color], verbose_name='Цвет'),
        ),
    ]
