# Generated by Django 3.2.3 on 2023-07-14 17:50

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[api.validators.validate_image], verbose_name='Изображение'),
        ),
    ]
